### ISSUE TITLE
Create a GitHub Template from this repo

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/terraform-aws-tfstate-backend#10]
As a maintainer of the UDS Terraform IaC modules, I want the ability to create a new Terraform module from a template, so that I don't need to redo the setup work each time.

**Acceptance Criteria:**

- I'm able to create a new Terraform module from a template that includes
    - [x] Common GitHub Actions workflow(s)
    - [x] ADR setup
    - [x] Terratest setup
    - [x] Checkov config
    - [x] Editorconfig
    - [x] Gitignore
    - [x] Golangci-lint config
    - [x] Pre-commit config
    - [x] Tool-versions
    - [x] CODEOWNERS
    -  [x] CONTRIBUTING
    - [x] LICENSE
    - [x] Makefile
    - [x] Renovate config
    - [x] README with terraform-docs needle
    - [x] main.tf with nothing in it (?)

Notes:

- Since we are establishing a pattern, with this repo being the first user of the new pattern, we should copy all the "boilerplate" stuff over to a template repo that can be used as a baseline when we create new repos.
- We can then follow up after that by having an automated action reconcile each repo against the template to find things that need to be updated and automatically create pull requests with the needed changes. That way we can centralize all this "boilerplate" in a way that is easy to keep updated.

**Comment by wirewc** [comment]
@RothAndrew I think we can close this now. 

Also, should UDS have the ability to approve this as well? Right now IaC members are required to be approvers only.

**Comment by wirewc** [comment]
I'm going to close this one now only because there was interest to not make a template repo right now. We have the pattern in place on this repo at this time so I feel like the scope of this ticket is worth closing. 

With that said, there is a UDS team I have created but I'm trying to add all the team members on there still.
