### ISSUE TITLE
Add a real Terratest test for this module

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/terraform-aws-tfstate-backend#12]
As a user of this module, I want it to be tested each time a change is made, so that I can be confident that changes that are made are of sufficient quality.

Acceptance Criteria:
- Module meets minimum requirements for testing as defined in https://github.com/defenseunicorns/uds-infra/blob/main/CONTRIBUTING.md

Notes:
- We need to add a real test for this module, using Terratest.
- ~~Do we want to just do our own thing, like how DI2-ME and `iac` does it now? Or do we want to go ahead and utilize [Unicorn Testing Framework](https://github.com/defenseunicorns/unicorn-testing-framework)? UTF has just had the "dash days treatment" but we could take it under our wing and use it for real (and keep improving it)~~ See [comment](https://github.com/defenseunicorns/terraform-aws-tfstate-backend/issues/12#issuecomment-1444469203)

**Comment by RothAndrew** [comment]
> Do we want to just do our own thing, like how DI2-ME and iac does it now? Or do we want to go ahead and utilize [Unicorn Testing Framework](https://github.com/defenseunicorns/unicorn-testing-framework)? UTF has just had the "dash days treatment" but we could take it under our wing and use it for real (and keep improving it)

@runyontr @blancharda opinions?

**Comment by blancharda** [comment]
I'd say if there's a simple way to utilize it now, that makes sense... But if it's going to take a significant amount of updating to UTF, maybe we collect that as potential work items for the next dash?

**Comment by RothAndrew** [comment]
For now, going with not using UTF, since these modules will actually have a slightly different purpose. We want to test the modules themselves vice being given a preconfigured environment where something else (like a zarf package) can be tested
