### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/terraform-aws-tfstate-backend#22]
As a user of this module, I want a sufficient level of documentation so that I know how to use it

Acceptance Criteria:
- This module meets the minimum requirements for documentation as defined in https://github.com/defenseunicorns/uds-infra/blob/main/CONTRIBUTING.md

**Comment by wirewc** [comment]
Needed to meet the documentation guidelines: 

* [ ] The module has a README.md that includes:
  * [ ] A description of the module
  * [ ] A Getting Started section
  * [ ] A list of required providers and their version constraint
  * [ ] A list of each module that this module consumes, with source and version
  * [ ] A list of the resources that the module creates
  * [ ] A list of the inputs with name, description, type, and default value
  * [ ] A list of the outputs with name and description
* [ ] The module has at least one example
