### ISSUE TITLE
Automatically generate the new remote backend

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/terraform-aws-tfstate-backend#33]
As a user of this module, I'd like the new terraform remote backend block to be generated for me after I have done a `terraform apply`, so that I don't need to create it manually.

Notes:
- [CloudPosse's similar module](https://github.com/cloudposse/terraform-aws-tfstate-backend) does this, and it is really easy to set up. It turns the whole process into just:

	```shell
	terraform init
	terraform apply
	terraform init -force-copy
	```
	
	resulting in the backend managing its own state, along with everything else
- We can set up so that the backend is optionally created, so that existing functionality is preserved.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/16000938/221702311-5b3fa805-699f-4d2c-b8e9-357aea3eb775.png">

**Comment by wirewc** [comment]
@RothAndrew I have the logic that we need (that has been tested and working) in a Zarf package [here](https://github.com/defenseunicorns/uds-pack-the-stack/blob/main/packages/bootstrap/zarf.yaml#L28-L50). Do we want a shell script to create and destroy the S3 bucket and DynamoDB table? Or is there some other mechanism we should be using?

**Comment by RothAndrew** [comment]
I like the way cloudposse does theirs. https://github.com/cloudposse/terraform-aws-tfstate-backend#create

**Comment by wirewc** [comment]
I have some scripts committed but I need to study how Cloud Posse does theirs. Thanks @RothAndrew!

**Comment by wirewc** [comment]
@RothAndrew the `state-manage` branch has the changes you are looking for. It looks like using Terraform and template with the `local_file` resource is more reliable than a shell script. There is an updated readme for the example for how to use the new functionality.
